{
    'name': 'BhuKhadan',
    'version': '18.0.1.5.7',
    'summary': 'BhuKhadan — Coal Bearing & Land Acquisition Management System.',
    'sequence':'-1',
    'description':'Digitize end-to-end land acquisition under the Coal Bearing Areas (Acquisition & Development) Act, 1957 and RFCTLARR Act, 2013 — from notification through award, ensuring transparency, traceability, and accountability.',
    'category': 'BhuKhadan',
    'website': 'bhuarjan.com',
    'depends': ['web', 'web_hierarchy', 'mail', 'auth_oauth', 'auth_signup', 'base_import'],
    'data':[
        # ---------------------------------------------------------------------
        # Master / seed data XML — disabled (live DB already populated).
        # Re-enable individual files only for fresh installs or deliberate reseed.
        # ---------------------------------------------------------------------
        # 'data/ir_sequence_data.xml',
        # 'data/ir_model_access_data.xml',
        # 'data/land_type_data.xml',
        # 'data/tree_master_data.xml',
        # 'data/photo_type_master_data.xml',
        # 'data/chhattisgarh_districts_data.xml',
        # 'data/raigarh_sub_division_data.xml',
        # 'data/raipur_sub_division_data.xml',
        # 'data/tehsil_data.xml',
        # 'data/raigarh_village_data.xml',
        # 'data/chhattisgarh_villages_data.xml',
        # 'data/department_data.xml',
        # 'data/indian_bank_master_data.xml',
        # 'data/settings_master_data.xml',
        # 'data/sample_project_data.xml',
        # 'data/sample_sequence_settings.xml',
        # 'data/sample_expert_committee_report.xml',
        # 'data/sample_landowners.xml',
        # 'data/sample_surveys.xml',
        # 'data/sample_section4_config.xml',
        # 'data/sample_section4_notifications.xml',
        # 'data/sample_section15_objections.xml',
        # 'data/sample_section11_reports.xml',
        # 'data/sample_section19_notifications.xml',
        # 'data/sample_process_data.xml',
        # 'data/kharsiyan_rate_master_data.xml',
        # 'data/section_master_data.xml',
        # 'data/cglrc_master_data.xml',
        # 'data/jurda_test_permutations.xml',
        # 'data/jurda_sample_surveys.xml',
        # 'data/mail_data.xml',
        'security/secrurity.xml',
        'security/ir.model.access.csv',
        'views/menu_structure.xml',
        'data/survey_photo_cron.xml',
        'data/sample_master_scope_import.xml',
        'data/coal_act_master_data.xml',
        'data/coal_runtime_gating.xml',
        # Report PDF layouts (not master/seed data; required by reports/*.xml refs)
        'data/qweb_report_paper_format.xml',
        'reports/report_common_styles.xml',
        'reports/form10_bulk_table_report.xml',
        'reports/form5_form6_dols_reports.xml',
        'reports/award_letter_report.xml',
        'reports/section4_notification_report.xml',
        'reports/section11_preliminary_report.xml',
        'reports/section19_notification_report.xml',
        'reports/section21_notification_report.xml',
        'reports/section8_order_report.xml',
        'reports/section9_notification_report.xml',
        'reports/draft_award_report.xml',
        'reports/sia_order_report.xml',
        'reports/sia_proposal_report.xml',
        'reports/expert_committee_proposal_report.xml',
        'reports/expert_committee_order_report.xml',
        'reports/section15_objection_resolution_report.xml',
        'reports/section23_award_report.xml',
        'reports/consolidated_award_report.xml',
        'reports/rr_award_report.xml',
        'reports/project_master_report.xml',
        'reports/tree_rate_master_report.xml',
        'reports/section247_cglrc_reports.xml',
        'reports/measuring_book_report.xml',
        'views/district_views.xml',
        'views/bhu_sub_division_views.xml',
        'views/bhu_tehsil_views.xml',
        'views/bhu_village_views.xml',
        'views/res_users_views.xml',
        'views/project_views.xml',
        'views/master_views.xml',
        'views/res_bank_views.xml',
        'views/landowner_views.xml',
        'views/house_owner_views.xml',
        'views/survey_views.xml',
        'views/survey_bulk_approval_wizard_views.xml',
        'views/document_vault_views.xml',
        'views/document_vault_navigator_views.xml',
        'views/sia_team_views.xml',
        'views/sia_team_member_views.xml',
        'wizard/sia_send_back_wizard.xml',
        'wizard/sia_download_wizard_views.xml',
        'wizard/award_download_wizard_views.xml',
        'wizard/s23_land_edit_wizard_views.xml',
        'wizard/s23_tree_edit_wizard_views.xml',
        'wizard/process_send_back_wizard.xml',
        'wizard/section8_approve_reject_wizard.xml',
        'wizard/reject_survey_wizard_views.xml',
        'views/section15_objection_views.xml',
        'views/process_stub_views.xml',
        'views/process_views.xml',
        'views/section4_notification_views.xml',
        'views/section11_preliminary_report_views.xml',
        'views/section19_notification_views.xml',
        'views/section21_notification_views.xml',
        'views/section18_rr_scheme_views.xml',
        'views/section8_views.xml',
        'views/section9_notification_views.xml',
        'views/section23_award_views.xml',
        'views/section23_award_survey_line_views.xml',
        'views/all_section_report_views.xml',
        'views/process_report_views.xml',
        'views/draft_award_views.xml',
        'views/dashboard_views.xml',
        'views/hierarchy_tree_views.xml',
        'views/expert_committee_report_views.xml',
        'views/message_wizard_views.xml',
        'views/company_switcher_views.xml',
        'views/post_award_payment_views.xml',
        'views/payment_reconciliation_views.xml',
        'views/payment_file_views.xml',
        'views/payment_voucher_views.xml',
        'views/payment_reconciliation_bank_views.xml',
        'views/payment_dashboard_views.xml',
        'views/land_rate_master_views.xml',
        'views/tree_master_views.xml',
        'views/law_master_views.xml',
        'views/section_master_views.xml',
        'views/section20a_railways_views.xml',
        'views/section20d_railways_views.xml',
        'views/section20e_railways_views.xml',
        'views/section3a_nh_views.xml',
        'views/section3c_nh_views.xml',
        'views/section3d_nh_views.xml',
        'views/section247_cglrc_views.xml',
        'views/photo_type_master_views.xml',
        'views/area_master_views.xml',
        'views/settings_master_views.xml',
        'views/jwt_token_views.xml',
        'views/mobile_otp_views.xml',
        'wizard/payment_voucher_generate_wizard_views.xml',
        'wizard/time_savings_report_wizard_views.xml',
        'wizard/report_wizard.xml',
        'wizard/user_report_wizard.xml',
        'wizard/survey_import_wizard_views.xml',
        'views/qr_microsite_templates.xml',
        'views/menu_root.xml',
        'views/group_dashboard_views.xml',
        'views/menuitem.xml',
        'views/issue_views.xml',
        'views/login_templates.xml',
        'views/layout_templates.xml',
        # Debranding views (merged from debrand_odoo module)
        'views/debrand_views.xml',
        # Password eyes icon views (merged from password_eyes_icon module)
        'views/password_eyes_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # 'bhukhadan_core/static/src/xml/mail_systray_hide_button.xml',
            # 'bhukhadan_core/static/src/css/rate_master_form.css',
            'bhukhadan_core/static/src/css/survey_status.css',
            'bhukhadan_core/static/src/css/section23_award_form_premium.css',
            'bhukhadan_core/static/src/css/payment_voucher_premium.css',
            'bhukhadan_core/static/src/css/time_savings_report.css',
            'bhukhadan_core/static/src/css/document_vault_navigator.css',
            'bhukhadan_core/static/src/js/docvault_navigator_form.js',
            'bhukhadan_core/static/src/js/docvault_navigator_ui.js',
            'bhukhadan_core/static/src/scss/comma_pills_char_field.scss',
            'bhukhadan_core/static/src/xml/bhu_comma_pills_char_field.xml',
            'bhukhadan_core/static/src/js/bhu_comma_pills_char_field.js',
            'bhukhadan_core/static/src/css/search_view.css',
            'bhukhadan_core/static/src/css/login_as_banner.css',
            'bhukhadan_core/static/src/css/bhu_approved_ribbon.css',
            'bhukhadan_core/static/src/css/bhuarjan_footer.css',
            'bhukhadan_core/static/src/css/bhu_terms_acceptance.css',
            'bhukhadan_core/static/src/js/bhu_terms_acceptance.js',
            'bhukhadan_core/static/src/js/login_as_banner.js',
            'bhukhadan_core/static/src/css/dashboard.css',
            # Dashboard files - organized in separate folders
            'bhukhadan_core/static/src/dashboard/css/admin_dashboard.css',
            'bhukhadan_core/static/src/dashboard/css/timeline_component.css',
            'bhukhadan_core/static/src/dashboard/xml/dashboard_header.xml',
            'bhukhadan_core/static/src/dashboard/xml/timeline_component.xml',
            'bhukhadan_core/static/src/dashboard/xml/admin_dashboard.xml',
            'bhukhadan_core/static/src/dashboard/js/web_client_dashboard.js',
            # Unified Dashboard (replaces separate JS files)
            'bhukhadan_core/static/src/dashboard/js/unified_dashboard.js',
            # SDM Dashboard files (CSS and XML only - JS is in unified_dashboard.js)
            'bhukhadan_core/static/src/dashboard/css/sdm_dashboard.css',
            'bhukhadan_core/static/src/dashboard/xml/sdm_dashboard.xml',
            # Department User Dashboard files (XML only - JS is in unified_dashboard.js)
            'bhukhadan_core/static/src/dashboard/xml/department_dashboard.xml',
            # Collector Dashboard XML (JS is shared with SDM)
            'bhukhadan_core/static/src/dashboard/xml/collector_dashboard.xml',
            # District Admin Dashboard XML (JS is in unified_dashboard.js)
            'bhukhadan_core/static/src/dashboard/xml/district_dashboard.xml',
            # Group Dashboard (for Administrators)
            'bhukhadan_core/static/src/dashboard/css/group_dashboard.css',
            'bhukhadan_core/static/src/dashboard/xml/group_dashboard.xml',
            'bhukhadan_core/static/src/dashboard/js/group_dashboard.js',
            'bhukhadan_core/static/src/dashboard/xml/sdm_pipeline_dashboard.xml',
            'bhukhadan_core/static/src/dashboard/js/sdm_pipeline_dashboard.js',
            'bhukhadan_core/static/src/dashboard/scss/management_dashboard.scss',
            'bhukhadan_core/static/src/dashboard/xml/management_dashboard.xml',
            'bhukhadan_core/static/src/dashboard/js/management_dashboard.js',
            # Unified theme overlay (shared dashboard chrome).
            'bhukhadan_core/static/src/dashboard/css/dashboards_unified_theme.css',
            # Mobile dashboard — must load after unified theme
            'bhukhadan_core/static/src/dashboard/css/dashboard_mobile.css',
            # SDM Pipeline overrides — load after unified theme (compact light header).
            'bhukhadan_core/static/src/dashboard/css/sdm_pipeline_dashboard.css',
            # Role-based Dashboard (routes to appropriate dashboard based on user role)
            'bhukhadan_core/static/src/dashboard/js/role_based_dashboard.js',
            # Payment Dashboard (OWL)
            'bhukhadan_core/static/src/dashboard/css/payment_dashboard.css',
            'bhukhadan_core/static/src/dashboard/xml/payment_dashboard.xml',
            'bhukhadan_core/static/src/dashboard/js/payment_dashboard.js',

            # 'bhukhadan_core/static/src/css/landowner_documents.css',
            'bhukhadan_core/static/src/scss/hierarchy_view.scss',
            'bhukhadan_core/static/src/scss/hierarchy_tree.scss',
            'bhukhadan_core/static/src/js/components/hierarchy_tree.js',
            # 'bhukhadan_core/static/src/scss/organization_chart.scss',
            # 'bhukhadan_core/static/src/js/hierarchy_expand.js',
            # 'bhukhadan_core/static/src/js/survey_form_confirm.js',
            'bhukhadan_core/static/src/js/support_issue.js',
            'bhukhadan_core/static/src/js/s23_download_and_refresh.js',
            # Register js_class="confirm_save_form" custom form view.
            'bhukhadan_core/static/src/js/components/popup.js',
            # Debranding assets (merged from debrand_odoo module)
            'bhukhadan_core/static/src/js/debrand_user_menu.js',
            'bhukhadan_core/static/src/xml/debrand_web.xml',
            # Password eyes icon assets (merged from password_eyes_icon module)
            'bhukhadan_core/static/src/scss/password_eyes_icon.scss',
            'bhukhadan_core/static/src/js/password_eyes_icon.js',
            'bhukhadan_core/static/src/js/password_eyes_icon_field.js',
            'bhukhadan_core/static/src/xml/password_eyes_icon.xml',
            # Timepicker assets (merged from timepicker module)
            'bhukhadan_core/static/src/xml/timepicker.xml',
            'bhukhadan_core/static/src/css/timepicker.css',
            'bhukhadan_core/static/src/js/timepicker.js',
            # Image Capture Widget (merged from image_capture_upload_widget module)
            # 'bhukhadan_core/static/src/scss/image_capture.scss',
            # 'bhukhadan_core/static/src/js/components/image_capture.js',
            # 'bhukhadan_core/static/src/xml/image_capture_templates.xml',
            'bhukhadan_core/static/src/scss/image_capture.scss',
            'bhukhadan_core/static/src/js/components/image_capture.js',
            'bhukhadan_core/static/src/xml/image_capture_templates.xml',
            # Project Timeline Widget
            'bhukhadan_core/static/src/scss/project_timeline.scss',
            'bhukhadan_core/static/src/js/components/project_timeline.js',
            'bhukhadan_core/static/src/xml/project_timeline.xml',
            # KML Viewer Component
            'bhukhadan_core/static/src/components/kml_viewer/kml_viewer.css',
            'bhukhadan_core/static/src/components/kml_viewer/kml_viewer.js',
            'bhukhadan_core/static/src/components/kml_viewer/kml_viewer.xml',
            'bhukhadan_core/static/src/xml/hierarchy_tree.xml',
            # Award action loader (shows overlay on generate/download button clicks)
            'bhukhadan_core/static/src/js/award_action_loader.js',
            # Header sorting for Section 23 HTML preview tables
            'bhukhadan_core/static/src/js/s23_preview_table_sort.js',
            'bhukhadan_core/static/src/js/payment_voucher_html_edit.js',
            'bhukhadan_core/static/src/js/payment_voucher_line_editor.js',
            'bhukhadan_core/static/src/css/spiffy_hide_right_panel.css',
        ],
        'web.assets_frontend': [
            'bhukhadan_core/static/src/scss/password_eyes_icon.scss',
            'bhukhadan_core/static/src/js/password_toggle_public.js',
        ],
        'web.assets_public': [
            'bhukhadan_core/static/src/scss/password_eyes_icon.scss',
            'bhukhadan_core/static/src/js/password_toggle_public.js',
        ],
    },
    'external_dependencies': {
        'python': ['jwt', 'requests'],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',

}
